### ISSUE TITLE
BEPS in julia is about 2x faster than C

### ISSUE THREAD

**Issue by kongdd** [JChen-UToronto/BEPS_hourly_site#5]
Julia is much easier to use, and more friendly to users.
It is amazing to find that BEPS in julia is about 2x faster than C.

The test case is at: https://github.com/CUG-hydro/BEPS.jl/blob/master/example_01.qmd.
Call for contributors for BEPS.jl.

**Comment by jacobjiyeleng** [comment]
Hi Dongdong,
Thanks for your kind suggestion. We would take this into consideration later on after finding the developer to convert the whole BEPS project into a more efficient one.
Thanks,
Jiye
